spring.application.name=lostAndFound
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/demodb
spring.datasource.password=Iusuallydontdothis
spring.datasource.username=postgres

spring.datasource.hikari.schema=Workshop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect