spring.application.name=lostAndFound
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/root
spring.datasource.password=
spring.datasource.username=

spring.datasource.hikari.schema=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgresSQLDialect